// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp00eyYOeH2TktN_odjo18JtFMPbwnuz0',
    appId: '1:66639516677:web:c32dbc2944ad83cde9786c',
    messagingSenderId: '66639516677',
    projectId: 'dtrapp-dc61f',
    authDomain: 'dtrapp-dc61f.firebaseapp.com',
    storageBucket: 'dtrapp-dc61f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUNx9so1mucCAQ4UjlQnFs4NUGfCWTBWs',
    appId: '1:66639516677:android:83389eef474d8663e9786c',
    messagingSenderId: '66639516677',
    projectId: 'dtrapp-dc61f',
    storageBucket: 'dtrapp-dc61f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXKVYQmSKiFMz3B1ZALDP43qFkLGscHWg',
    appId: '1:66639516677:ios:e2997e122b6e3a40e9786c',
    messagingSenderId: '66639516677',
    projectId: 'dtrapp-dc61f',
    storageBucket: 'dtrapp-dc61f.firebasestorage.app',
    iosClientId: '66639516677-voh7puo7mkl3s0psthp36qchvnk448b3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXKVYQmSKiFMz3B1ZALDP43qFkLGscHWg',
    appId: '1:66639516677:ios:e2997e122b6e3a40e9786c',
    messagingSenderId: '66639516677',
    projectId: 'dtrapp-dc61f',
    storageBucket: 'dtrapp-dc61f.firebasestorage.app',
    iosClientId: '66639516677-voh7puo7mkl3s0psthp36qchvnk448b3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp00eyYOeH2TktN_odjo18JtFMPbwnuz0',
    appId: '1:66639516677:web:25fd842b16566f04e9786c',
    messagingSenderId: '66639516677',
    projectId: 'dtrapp-dc61f',
    authDomain: 'dtrapp-dc61f.firebaseapp.com',
    storageBucket: 'dtrapp-dc61f.firebasestorage.app',
  );
}
