target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_installation

  flutter_root = ENV['FLUTTER_ROOT']
  unless flutter_root
    raise "FLUTTER_ROOT environment variable is not set. Codemagic should provide it."
  end

  load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')
  install_all_flutter_pods
end
