platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_installation
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_installation

  flutter_root = File.expand_path('..', __FILE__) + '/..'
  load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')
  install_all_flutter_pods(flutter_root)
end
